# Generated by Django 4.2.20 on 2025-04-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_charitypagedata_charity_link_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='image',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='play',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
