# Generated by Django 4.2.20 on 2025-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_image_options_alter_play_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='play',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='display_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
