# Generated by Django 4.2.20 on 2025-04-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_image_display_order_alter_play_display_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='play',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='display_order',
            field=models.IntegerField(default=1),
        ),
    ]
