# Generated by Django 4.2.20 on 2025-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_prepare_uniqueness_alter_image_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='display_order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='display_order',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='display_order',
            field=models.IntegerField(unique=True),
        ),
    ]
