# Generated by Django 4.2.20 on 2025-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_image_display_order_alter_play_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aspect_ratio',
            field=models.CharField(choices=[('normal', 'normal'), ('portrait', 'portrait')], default='normal', max_length=8),
        ),
    ]
